### ISSUE TITLE
Questions related to your AMD Stable diffusion post

### ISSUE THREAD

**Issue by dilflydutiful** [initialxy/initialxy.github.io#15]
I apologize for posting here, but this the closest relevant project I could find. I currently have an AMD 7900XT gpu and found your blog post about getting Stable Diffusion to work on amd gpu with linux very informative. I am currently running SD on the vulkan based windows app, shark, put out by nod.ai. It is not optimized and lacks lots of the newer features, like training. I wanted to reach out and ask some questions about the limitations you saw with your installation and more specifically around training. 

I am tempted to just buy a used 3090 and put it in a lean system to just run SD batches. This is only attractive if there are significant limitation (beyond speed) that using an AMD chip presents.  These are some of the questions I had to decide my path, and please feel free to interject any other information that you may think is related, Also, thank you in advance.  

Were you able to use a current version of SD? 
Also were any features not enabled due to non-nvidia gpu?
What linux distro did you find worked best? I have read that Arch linux is needed on most write ups, was this the case for you? 

I have a technical background but do not use linux often anymore due to working a second line grc role now. I plan on dual booting an arch linux distro on my local PC assuming the above stated limits are not met. 

Please let me know what you think and thanks again.

**Comment by initialxy** [comment]
Hey thanks for reaching out. Glad you read my post.

> Were you able to use a current version of SD?

I use [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and I update it regularly. I haven't been limited by its feature or any extensions yet. 

> Also were any features not enabled due to non-nvidia gpu?

In regular use, no. However in training, AMD GPU has no support for xformer and 8bitAdam. Those are speed and VRAM optimization techniques. You can train without them. Though for me, I couldn't get Dreambooth training going due to running out of VRAM. Since 8bitAdam was not available for me to optimize VRAM usage, so that's a dead end for me. Your 7900 XT has 20 GB VRAM vs my 6700 XT's 12 GB, so maybe that's worth a try. I also didn't attempt Dreambooth training again on kohya_ss recently, so maybe there were some developments.

> What linux distro did you find worked best? I have read that Arch linux is needed on most write ups, was this the case for you?

Arch is just what I use. I personally wouldn't recommend Arch to someone else unless they are already very familiar with Linux. You just need a distro with recent enough version of Python. I believe Ubuntu or Fedora will work fine as long as it's not based on LTS (eg. ElementaryOS, which tend to stay behind). But even if a distro doesn't have a newer version of Python, you can still install it one way or another. stable-diffusion-webui requires [Python 3.10.6](https://www.python.org/downloads/windows/). Ubuntu 22.10 has [3.10.6](https://packages.ubuntu.com/search?keywords=python3) so it will do. Though the package name is `python3`.

Let me know if you have more questions.

**Comment by initialxy** [comment]
I tried Dreambooth training on the current version of kohya_ss again just out of curiosity, unfortunately I still ran out of VRAM right away with Lion optimizer.
